
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgkdegvakeapaidifbnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNna2RlZ3Zha2VhcGFpZGlmYm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTc5NTQsImV4cCI6MjA1ODg5Mzk1NH0.78dPTMrb3RpCWA4RdupuvywvkTzq1NSeroAZOmvWz7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
